bookingDoctor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from api import urls as api_urls
import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required, permission_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^api/', include(api_urls)),
    url(r'^$', views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^singup/$', views.signup, name='signup'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.ProfileUser.as_view(), name='profile'),
    url(r'^appointment/book/$', views.AppointmentBook.as_view(), name='appointment-book'),
    url(r'^appointment/(?P<pk>[0-9]+)/$', views.AppointmentDetail.as_view(), name='appointment-detail'),
    url(r'^patients/$', views.PatientListView.as_view(), name='patients'),
    url(r'^appointment/me/$', views.AppointmentMe.as_view(), name='appointment-me'),
    url(r'^appointment/change/$', views.AppointmentUpdate.as_view(), name='appointment-update'),
    url(r'^feedback/$', views.FeebackCreate.as_view(), name='feedback'),
    # url(r'^detail/user/(?P<pk>[0-9]+)/$', views.DetailUser.as_view(), name='profile'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL.replace(settings.SITE_URL, ''), document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL.replace(settings.SITE_URL, ''), document_root=settings.MEDIA_ROOT)

api/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import AbstractUser

class UserBase(AbstractUser):
    PATIENT = 1
    DOCTOR = 2
    ROLE_CHOICES = (
        (PATIENT, _('Patient')),
        (DOCTOR, _('Doctor')),
    )

    CONST_GENDER_FEMALE = 0
    CONST_GENDER_MALE = 1
    CONST_GENDER_BOTH = 2
    CONST_GENDERS = (
        (CONST_GENDER_FEMALE, _('Female')),
        (CONST_GENDER_MALE, _('Male')),
        (CONST_GENDER_BOTH, _('Both')),
    )

    phone = models.CharField(max_length=250, null=True, blank=True)
    address = models.CharField(max_length=250, null=True, blank=True)
    sex = models.PositiveSmallIntegerField(_('sex'), choices=CONST_GENDERS, \
                                              default=CONST_GENDER_MALE)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, default=DOCTOR, null=True, blank=True)

    @property
    def full_name(self):
        return u'{} {}'.format(self.first_name,self.last_name)

class Patient(models.Model):
    user = models.OneToOneField(UserBase, on_delete=models.CASCADE)
    dob = models.DateField(_('DOB'), null=True, blank=True)

    def __unicode__(self):
        return self.user.full_name


class Doctor(models.Model):
    user = models.OneToOneField(UserBase, on_delete=models.CASCADE)
    category = models.CharField(max_length=250, null=True, blank=True)

    def __unicode__(self):
        return self.user.full_name

@receiver(post_save, sender=UserBase)
def create_doctor(sender, instance, created, **kwargs):
    if created and instance.role==UserBase.DOCTOR:
        Doctor.objects.create(user=instance)

class Appointment(models.Model):
    patient = models.ForeignKey(Patient, related_name='patient_appointment')
    doctor = models.ForeignKey(Doctor, related_name='doctor_appointment')
    creation_date = models.DateTimeField(auto_now_add=True)
    last_change = models.DateTimeField(null=True, blank=True)
    appointment = models.DateTimeField()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.last_change = timezone.now()
        super(Appointment, self).save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        return reverse('appointment-detail', kwargs={'pk': self.pk})
        
class Treatment(models.Model):
    patient = models.ForeignKey(Patient, related_name='patient_treatment')
    doctor = models.ForeignKey(Doctor, related_name='doctor_treatment')
    creation_date = models.DateTimeField(auto_now_add=True)
    last_change = models.DateTimeField(null=True, blank=True)
    treatment = models.CharField(max_length=250, null=True, blank=True)
    treatment_for = models.CharField(max_length=250, null=True, blank=True)
    dnote = models.CharField(max_length=250, null=True, blank=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.last_change = timezone.now()
        super(Treatment, self).save(force_insert, force_update, using, update_fields)

class Schedule(models.Model):    
    creation_date = models.DateTimeField(auto_now_add=True)
    last_change = models.DateTimeField(null=True, blank=True)
    note = models.CharField(max_length=250, null=True, blank=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.last_change = timezone.now()
        super(Schedule, self).save(force_insert, force_update, using, update_fields)

class Feedback(models.Model):
    patient = models.ForeignKey(Patient, related_name='patient_feedback')
    creation_date = models.DateTimeField(auto_now_add=True)
    feedback = models.TextField()

bookingDoctor/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from form import *
from api.models import *
from django.contrib.auth import authenticate, login

from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


def home(request):
    return render(request, 'home.html')


def signup(request):
    if request.method == 'POST':

        signup_form = SignUpForm(request.POST)

        if signup_form.is_valid():
            signup_form.save()
            patient = Patient.objects.create(user=signup_form.instance, dob=signup_form.cleaned_data.get('dob'))
            username = signup_form.cleaned_data.get('username')
            password1 = signup_form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=password1)
            
            if user is not None:
                login(request, user)
                return redirect('home')
        return render(request, 'signup.html', {'signup_form': signup_form})

    else:
        signup_form = SignUpForm()
    return render(request, 'signup.html', {'signup_form': signup_form})


class ProfileUser(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = UserBase
    form_class = EditMultiForm
    template_name = 'profile.html'

    def get_form(self):
        form = super(ProfileUser, self).get_form()
        if self.request.user.role == UserBase.PATIENT:
            return UserPatientForm(**self.get_form_kwargs())
        if self.request.user.role == UserBase.DOCTOR:
            return UserDoctorForm(**self.get_form_kwargs())

    def get_success_url(self):
        return u'/profile/%d' % self.request.user.id 


    def get_form_kwargs(self):
        kwargs = super(ProfileUser, self).get_form_kwargs()
        if self.request.user.role == UserBase.PATIENT:
            kwargs.update(instance={'patient': self.object.patient,'user': self.object,})
        if self.request.user.role == UserBase.DOCTOR:
            kwargs.update(instance={'user': self.object,'doctor': self.object.doctor})
        return kwargs

class PatientListView(ListView):
    model = Patient
    template_name = 'patients.html'
    
    def get_queryset(self):
        appointment_id = Appointment.objects.filter(doctor_id = self.request.user.doctor.id)
        patient = Patient.objects.filter( patient_appointment__in = appointment_id)
        return patient


class AppointmentBook(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    template_name = "appointment_book.html"
    model = Appointment
    fields = ('doctor', 'appointment')

    def form_valid(self, form):
        form.instance.patient = self.request.user.patient
        return super(AppointmentBook,self).form_valid(form)


class AppointmentDetail(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    queryset = Appointment.objects.all()
    template_name = 'appointment_detail.html'
    context_object_name = 'appointment'
    def get_object(self):
        # Call the superclass
        object = super(AppointmentDetail,self).get_object()
        # Record the last accessed date
        object.last_change = timezone.now()
        object.save()
        # Return the object
        return object

class AppointmentMe(LoginRequiredMixin, ListView):
    login_url = '/login/'
    queryset = Appointment.objects.all()
    template_name = 'appointment_list.html'
    context_object_name = 'appointments'

    def get_queryset(self):
        if self.request.user.role == UserBase.PATIENT:
            return Appointment.objects.filter(patient=self.request.user.patient).order_by('-creation_date')
        return Appointment.objects.filter(doctor=self.request.user.doctor).order_by('appointment')

class AppointmentUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Appointment
    fields = ('doctor', 'appointment')
    template_name = "appointment_book.html"

    def get_object(self, queryset=None):
        return Appointment.objects.filter(patient=self.request.user.patient).order_by('creation_date').last()

class FeebackCreate(CreateView):
    model = Feedback
    fields = ['feedback']
    template_name = 'feedback.html'
    success_url = '/'

    def form_valid(self, form):
        form.instance.patient = self.request.user.patient
        self.object = form.save()
        return super(FeebackCreate, self).form_valid(form)

bookingDoctor/templates/appointment_book.html
{% extends 'home.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}
{{ block.super}}
<form action="" method="post">
    {% csrf_token %}
    <div class="container">
	    <div class="row">
	        <div class='col-xs-12 col-sm-4'>
	        	{{form.doctor.label}}:
	            <div class="form-group">
	                <div class='input-group'>
	                    {{ form.doctor | attr:"style:width:100%;height:33px" }}
	                </div>
	            </div>
	        </div>
	    </div>
	    <div class="row">
	        <div class='col-xs-12 col-sm-4'>
	        	{{form.appointment.label}}:
	            <div class="form-group">
	                <div class='input-group date' id='datetimepicker1'>
	                    {{form.appointment | attr:"class:form-control"}}
	                    <span class="input-group-addon">
	                        <span class="glyphicon glyphicon-calendar"></span>
	                    </span>
	                </div>
	            </div>
	            <input type="submit" value='{% if request.resolver_match.url_name == "appointment-book" %}Create{% else %}Update{% endif %}' class="btn btn-default" />
	        </div>
	    </div>

  	</div>
</form>
{% endblock %}

{% block js_content %}
	<script type="text/javascript">
    	$(function () {
        	$('#datetimepicker1').datetimepicker({
        		format : 'YYYY-MM-DD HH:mm:ss'
        	});
    	});
    </script>
{% endblock%}

bookingDoctor/templates/appointment_detail.html
{% extends 'home.html' %}

{% block content %}
{{ block.super}}
<div class="alert alert-info" role="alert">Appointment id: {{ appointment.id }}<br><br>
Creation date:{{ appointment.creation_date }}
Last change:{{ appointment.last_change }}<br>
Doctor:{{ appointment.doctor}}
Appointment date:{{ appointment.appointment}}

</div> 
{% endblock %}

bookingDoctor/templates/appointment_list.html
{% extends 'home.html' %}

{% block content %}
{{ block.super}}
{% for appointment in appointments %}
<div class="alert  {% if appointments.0 == appointment %} alert-info {% else %} alert-warning {% endif %}" role="alert">Appointment id: {{ appointment.id }}<br><br>
Creation date: {{ appointment.creation_date }} *** 
Last change: {{ appointment.last_change }}<br><br>
{% if request.user.role == 2 %}
Patient: <a href="#">{{ appointment.patient}}</a><br>
{% else %}
Doctor: {{ appointment.doctor}}<br>
{% endif %}
Appointment date: {{ appointment.appointment}}
</div> 
{% endfor %}

{% endblock %}

bookingDoctor/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %} Doctor Appointment Booking System {% endblock %}</title>

    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
    {% block body %}
    
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}"> Doctor Appointment Booking System </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
              <ul class="navbar-nav navbar-right">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="{% url 'profile' user.id %}">My Profile</a>
                    <a class="dropdown-item" href="#">Change password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                  </div>
                </li>
              </ul>

            {% else %}
              <ul class="navbar-nav navbar-right">
              <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
              </form>
              </ul>
            {% endif %}
          </div>
        </div>
      </nav>

      <div class="container">
        <ol class="breadcrumb my-4">
          {% block breadcrumb %}
          {% endblock %}
        </ol>
        {% block content %}
        {% endblock %}
      </div>
    {% endblock body %}
  </body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>   
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>   
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
  {% block js_content %}
  {% endblock%}
</html>

bookingDoctor/templates/feedback.html
{% extends 'home.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}
{{ block.super}}
<div class="col-lg-offset-1 feedback">
<form action="" method="post" id="form">
    {% csrf_token %}
    <div class="container">
	    <div class="row">
	        <div class=' col-xs-12 col-sm-4 '>
	        	{{form.feedback.label}}:
	            <div class="form-group">
	                <div class='input-group'>
	                    {{ form.feedback | attr:"style:width:100%;height:200px" }}
	                </div>
	            </div>
	        </div>
	    </div>
  	</div>
  	<button type="submit" class="btn btn-success" id="create">Create</button>
</form>
</div>
<br>
<br>
<p class="col-lg-offset-1" id="tks" style="display: none;">Thank for your feedback.</p>
{% endblock %}
{% block js_content %}
<script>
$("#create").click(function($event){
	$event.preventDefault();
    $("#tks").show();
    setTimeout(function(){
        $("#tks").hide();
    	$('#form').submit();
    }, 2000);
});
</script>
{% endblock %}

bookingDoctor/templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}


{% endblock %}

<div class="container mycontent">

  {% block content %}
  <div id="menu">
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th>Home</th>
          <th>Gallery</th>
          <th>Our staff</th>
          <th>About Us</th>
          <th>Contact Us</th>
        </tr>
      </thead>
    </table>
    {% if user.is_authenticated and user.role == 1 %}
     <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th class='{% if request.resolver_match.url_name == "profile" %}active{% endif %}'><a href="{% url 'profile' user.id %}">My Detail</a></th>
          <th class='{% if request.resolver_match.url_name == "appointment-book" %}active{% endif %}'><a href="{% url 'appointment-book' %}">Book Appointment</a></th>
          <th class='{% if request.resolver_match.url_name == "appointment-me" %}active{% endif %}'><a href="{% url 'appointment-me' %}">View Booking</th>
          <th class='{% if request.resolver_match.url_name == "appointment-update" %}active{% endif %}'><a href="{% url 'appointment-update' %}">Reschedule Booking</th>
          <th class='{% if request.resolver_match.url_name == "feedback" %}active{% endif %}'><a href="{% url 'feedback' %}">Feedback</th>
        </tr>
      </thead>
    </table>
    {% endif %}
    {% if user.is_authenticated and user.role == 2 %}
     <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th class='{% if request.resolver_match.url_name == "appointment-me" %}active{% endif %}'><a href="{% url 'appointment-me' %}">My Appointment</th>
          <th class='{% if request.resolver_match.url_name == "patients" %}active{% endif %}'><a href="{% url 'patients' %}">View Custumer</a></th>
          <th>Add Description</th>
          <th class='{% if request.resolver_match.url_name == "profile" %}active{% endif %}'><a href="{% url 'profile' user.id %}">My Detail</a></th>
        </tr>
      </thead>
    </table>
    {% endif %}
  </div>
  {% endblock %}

</div>

bookingDoctor/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h3>Log in to Doctor Appointment Booking System </h3>
    {% if form.errors %}
      <p style="color: red">Your username and password don't correct.</p>
    {% endif %}
    <div class="col-lg-4">
      <form method="post">
      {% csrf_token %}
      <!-- {{form.as_p}} -->
      <div class="form-group">
        <label for="id_username">Username</label>
        <input type="text" name="username"  class="form-control" autofocus="" required="" id="id_username" maxlength="254">
      </div>
      <div class="form-group">
        <label for="id_password">Password</label>
       <input type="password" class="form-control" name="password" required="" id="id_password">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
      <a href="{% url 'signup' %}">Sign up</a>
    </form>
    </div>
{% endblock %}

bookingDoctor/templates/patients.html
{% extends 'home.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
  {{ block.super }}

<div class="container">
  <h2>List Patient</h2>
  <table class="table table-striped">
  {% if patient_list %}
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Sex</th>
        <th>Address</th>
        <th>Birthday</th>
      </tr>
    </thead>
    <tbody>
      {% for patient in patient_list %}
        <tr >
          <td>{{patient.user.first_name}}</td>
          <td>{{patient.user.last_name}}</td>
          <td>{{patient.sex}}</td>
          <td>{{patient.address}}</td>
          <td>{{patient.dob}}</td>
        </tr>
      {% endfor %}

    </tbody>
  </table>
    {% else %}
      <p>There are no patient .</p>
    {% endif %}       
</div>
{% endblock %}
<!-- onclick="window.location='{% url "profile" patient.user.id %}';" -->

bookingDoctor/templates/profile.html
{% extends 'home.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
  {{ block.super }}
  <div class="row">
    <div class="col-lg-4">
      <div  align="center"> <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" style="width:80%;" id="profile-image1" class="img-circle img-responsive">
        <input id="profile-image-upload" class="hidden" type="file">
      </div>
      <br>
    </div>
    <div class="col-lg-offset-1 col-lg-7">
      <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="row">
            <div class="col-lg-5">
              {{ field.errors }}
              <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
              </div>
            </div>
          </div>
        {% endfor %}
        <input type="submit" class="btn btn-success" value="Update" />
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block js_content %}
  <script type="text/javascript">
      $(function () {
        $('#datetimepicker4').datetimepicker({
          format : 'YYYY-MM-DD'
        });
      });
    </script>
{% endblock%}

bookingDoctor/templates/signup.html
{% extends 'base.html' %}



{% block content %}

	<h2>Sign up for a free account</h2>
	<!-- <p class="lead">Select below the type of account you want to create</p> -->
	<!-- <a href="{% url 'signup' %}" class="btn btn-patient btn-lg" role="button">I'm a patient</a> -->
	<!-- <a href="{% url 'signup' %}" class="btn btn-doctor btn-lg" role="button">I'm a doctor</a> -->
	
	<form method="post">
		{% csrf_token %}
			<p style="color: red">{{ signup_form.errors }}</p>
		<div class="row">
			<div class="col-lg-4">
				<div class="form-group">
					<label for="id_username">Username:</label><br>
					<input type="text" name="username" class="form-control" autofocus required id="id_username" maxlength="150" />
				</div>
				
				<div class="form-group">
					<label for="id_first_name">First name:</label><br>
					<input type="text" name="first_name" class="form-control" required id="id_first_name" maxlength="30" />
				</div>
				
				
				
				<div class="form-group">
					<label for="id_email">Email:</label><br>
					<input type="email" name="email" class="form-control" required id="id_email" maxlength="254" />
				</div>
				
				<div class="form-group">
					<label for="id_password1">Password:</label><br>
					<input type="password" name="password1" class="form-control" required id="id_password1" />
				</div>
				<div class="form-group">
					<label for="id_dob">Date of birth:</label><br>
					<div class='input-group date' id='datetimepicker1'>
						<input type="text" name="dob" required class="form-control" id="id_dob" />
						<span class="input-group-addon">
	                        <span class="glyphicon glyphicon-calendar"></span>
	                    </span>
	                </div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="form-group">
					<label for="id_sex">Sex:</label><br>
					<select name="sex" id="id_sex" class="form-control">
						<option value="0">Female</option>
						<option value="1" selected>Male</option>
						<option value="2">Both</option>
					</select>
				</div>
				<div class="form-group">
					<label for="id_last_name">Last name:</label><br>
					<input type="text" name="last_name" class="form-control" required id="id_last_name" maxlength="30" />
				</div>
				<div class="form-group">
					<label for="id_phone">Phone:</label><br>
					<input type="text" name="phone" class="form-control" id="id_phone" maxlength="250" />
				</div>
				<div class="form-group">
					<label for="id_password2">Password confirmation:</label><br>
					<input type="password" name="password2" class="form-control" required id="id_password2" />
				</div>
				<div class="form-group">
					<label for="id_address">Address:</label><br>
					<input type="text" name="address" id="id_address" class="form-control" maxlength="250" />
				</div>
			</div>
		</div>
			<select name="role" id="id_role" style="display: none;">
			  <option value="1" selected="selected" >Patient</option>
			  <option value="2">Doctor</option>
			</select>
		<button type="submit" class="btn btn-success">Sign up</button>
	</form>

	
{% endblock %}

{% block js_content %}
<script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker({
                 format: 'DD/MM/YYYY'
           		});
            });
        </script>
{% endblock %}

bookingDoctor/templates/signup_form.html
{% extends 'base.html' %}

{% block content %}

  <h2>Sign up</h2>

  <form method="post">

    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }} <br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey"> {{ field.help_text }} </small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }} </p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
    Already have an account? <a href="{% url 'login' %}">Log in</a>

  </form>

{% endblock %}